services:
  - type: web
    name: airbnc-api
    runtime: node
    rootDir: api
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
